wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716130357
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.12.2
      5: 0.17.0
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 64
classes:
  desc: null
  value: 10
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.04814868888172391
