wandb_version: 1

_items:
  desc: null
  value:
    _wandb: {}
    batch_size: 32
    classes: 10
    epochs: 5
    learning_rate: 0.05366512260532099
_locked:
  desc: null
  value:
    batch_size: 0
    classes: 0
    epochs: 0
    learning_rate: 0
_users:
  desc: null
  value:
    sweep: 0
_users_inv:
  desc: null
  value:
    '0': sweep
_users_cnt:
  desc: null
  value: 1
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value:
    _args: null
    _aws_lambda: false
    _cli_only_mode: null
    _code_path_local: null
    _colab: false
    _cuda: null
    _disable_meta: false
    _disable_service: false
    _disable_setproctitle: false
    _disable_stats: false
    _disable_update_check: null
    _disable_viewer: null
    _disable_machine_info: false
    _executable: /home/student/anaconda3/envs/db_hw/bin/python
    _extra_http_headers: null
    _file_stream_retry_max: 125
    _file_stream_retry_wait_min_seconds: 2.0
    _file_stream_retry_wait_max_seconds: 60.0
    _file_stream_timeout_seconds: 180.0
    _file_transfer_retry_max: 20
    _file_transfer_retry_wait_min_seconds: 2.0
    _file_transfer_retry_wait_max_seconds: 60.0
    _file_transfer_timeout_seconds: 0.0
    _flow_control_custom: false
    _flow_control_disabled: false
    _graphql_retry_max: 20
    _graphql_retry_wait_min_seconds: 2.0
    _graphql_retry_wait_max_seconds: 60.0
    _graphql_timeout_seconds: 30.0
    _internal_check_process: 8.0
    _internal_queue_timeout: 2.0
    _ipython: false
    _jupyter: true
    _jupyter_name: null
    _jupyter_path: null
    _jupyter_root: null
    _kaggle: false
    _live_policy_rate_limit: null
    _live_policy_wait_time: null
    _log_level: 10
    _network_buffer: null
    _noop: false
    _notebook: true
    _offline: false
    _sync: false
    _os: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
    _platform: linux
    _proxies: null
    _python: 3.12.2
    _runqueue_item_id: null
    _require_core: false
    _save_requirements: true
    _service_transport: null
    _service_wait: 30.0
    _shared: false
    _start_datetime: '20240519_235106'
    _start_time: 1716130266.6082191
    _stats_pid: 20638
    _stats_sample_rate_seconds: 2.0
    _stats_samples_to_average: 15
    _stats_join_assets: true
    _stats_neuron_monitor_config_path: null
    _stats_open_metrics_endpoints: null
    _stats_open_metrics_filters:
    - .*
    _stats_disk_paths:
    - /
    _stats_buffer_size: 0
    _tmp_code_dir: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/tmp/code
    _tracelog: null
    _unsaved_keys: null
    _windows: false
    allow_val_change: null
    anonymous: null
    api_key: null
    azure_account_url_to_access_key: null
    base_url: https://api.wandb.ai
    code_dir: null
    colab_url: null
    config_paths: null
    console: wrap
    deployment: cloud
    disable_code: false
    disable_git: false
    disable_hints: null
    disable_job_creation: false
    disabled: false
    docker: null
    email: kym990708@gm.gist.ac.kr
    entity: ymkim78
    files_dir: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/files
    force: null
    fork_from: null
    git_commit: a7db1153d81484985b0f6aa9afa7f97210cd6db2
    git_remote: origin
    git_remote_url: https://github.com/doublecolor/db_hw_2.git
    git_root: null
    heartbeat_seconds: 30
    host: KYM-PC
    ignore_globs: []
    init_timeout: 90.0
    is_local: false
    job_name: null
    job_source: null
    label_disable: null
    launch: null
    launch_config_path: null
    log_dir: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/logs
    log_internal: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/logs/debug-internal.log
    log_symlink_internal: /home/student/db_hw_2/wandb/debug-internal.log
    log_symlink_user: /home/student/db_hw_2/wandb/debug.log
    log_user: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/logs/debug.log
    login_timeout: null
    mode: online
    notebook_name: null
    program: <python with no main file>
    program_abspath: null
    program_relpath: null
    project: your_project_name
    project_url: https://wandb.ai/ymkim78/your_project_name
    quiet: null
    reinit: null
    relogin: null
    resume: null
    resume_fname: /home/student/db_hw_2/wandb/wandb-resume.json
    resumed: false
    root_dir: /home/student/db_hw_2
    run_group: null
    run_id: wv5rnz24
    run_job_type: null
    run_mode: run
    run_name: cosmic-sweep-1
    run_notes: null
    run_tags: null
    run_url: https://wandb.ai/ymkim78/your_project_name/runs/wv5rnz24
    sagemaker_disable: null
    save_code: null
    settings_system: /home/student/.config/wandb/settings
    settings_workspace: /home/student/db_hw_2/wandb/settings
    show_colors: null
    show_emoji: null
    show_errors: true
    show_info: true
    show_warnings: true
    silent: false
    start_method: null
    strict: null
    summary_errors: null
    summary_timeout: 60
    summary_warnings: 5
    sweep_id: tcj781aa
    sweep_param_path: /home/student/db_hw_2/wandb/sweep-tcj781aa/config-wv5rnz24.yaml
    sweep_url: https://wandb.ai/ymkim78/your_project_name/sweeps/tcj781aa
    symlink: true
    sync_dir: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24
    sync_file: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/run-wv5rnz24.wandb
    sync_symlink_latest: /home/student/db_hw_2/wandb/latest-run
    system_sample: 15
    system_sample_seconds: 2
    table_raise_on_max_row_limit_exceeded: false
    timespec: '20240519_235106'
    tmp_dir: /home/student/db_hw_2/wandb/run-20240519_235106-wv5rnz24/tmp
    username: student
    wandb_dir: /home/student/db_hw_2/wandb/
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716130277
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.12.2
      5: 0.17.0
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 32
classes:
  desc: null
  value: 10
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.05366512260532099
