wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716124090
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 23
      - 24
      4: 3.12.2
      5: 0.17.0
      6: 4.40.1
      8:
      - 5
      13: linux-x86_64
